version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.16"
        PHOENIX_VERSION: "1.7.14"
        NODE_VERSION: "20.14.0"

    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:16.3
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: braiseapp
      POSTGRES_PASSWORD: braiseapp_pass
      POSTGRES_DB: braise_dev

volumes:
  postgres-data:
